In [23]:
from sklearn.cluster import AgglomerativeClustering
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.io import loadmat , whosmat
import sys
from scipy.stats import multivariate_normal
from sklearn import preprocessing
from sklearn.decomposition import PCA
from scipy.cluster.hierarchy import linkage, fcluster
from scipy.spatial.distance import pdist
from scipy.cluster.hierarchy import single, cophenet

In [21]:


path = r'C:\Users\johan\Documents\Documents\School\EDA_course\9781498776066_eda_toolbox_v3\EDA Toolbox V3\lungB.mat'
data = loadmat(path,simplify_cells=True)
type(data['lungB'])
X=data['lungB'].T
X=pd.DataFrame(X)

In [22]:
X.head()

,0,1,2,3,4,5,6,7,8,9,...,665,666,667,668,669,670,671,672,673,674
0,193.19,2565.55,3361.85,3810.86,2975.29,1158.14,3624.85,867.60,15.40,3828.42,...,56.710,107.010,14.59,317.230,350.78,41.310,700.730,269.020,136.250,0.000
1,369.52,2362.42,3262.46,2616.13,28.23,861.70,2553.35,440.19,62.21,3341.44,...,146.060,310.320,31.42,177.890,145.00,20.800,150.310,184.260,259.510,19.740
2,169.81,1861.83,2967.65,2563.59,41.46,1003.13,2186.26,435.66,17.39,3021.26,...,68.875,533.595,67.47,233.535,505.31,16.370,352.660,153.905,183.985,42.830
3,305.46,2340.89,3473.33,2876.46,2201.87,1006.68,2120.11,470.53,543.77,3004.02,...,397.170,207.935,9.26,302.845,299.91,22.695,333.215,293.380,149.810,132.565
4,413.63,2317.04,3340.84,3354.31,4.09,1380.59,2648.59,750.58,46.62,3190.31,...,280.920,344.320,122.49,236.580,306.09,25.360,24.350,260.770,186.130,93.170

In [ ]:
x_log=np.log2(X+1)
scaler= preprocessing.StandardScaler(with_mean=True, with_std=True)
x_scaled= scaler.fit_transform(x_log)

pca = PCA(svd_solver="full")  

score = pca.fit_transform(x_scaled)
explained=pca.explained_variance_ratio_*100

k = np.argmax(np.cumsum(explained) >= 95) + 1 # add eigenvalues in order until we get 90 comulative variance
Y = score[:, :k]
z=linkage(Y,method='ward',metric='euclidean')
T=fcluster(z, t=2, criterion="maxclust" )
d=pdist(Y,metric='euclidean')
c,d= cophenet(z,d)
c

np.float64(0.4184120615463215)

### My own agglomerative model based
# mle complete
# merge criteria uncomplete
# stopade criteria uncomplete

In [ ]:
def clusterCalculateMLE(cluster1):
    x=np.asanyarray(cluster1)
    n, d = x.shape
    e=sys.float_info.epsilon
    
    mu = x.mean(axis=0)
    sigma= np.cov(x, rowvar=False)
    print(sigma.shape)
    if(n==1):
        sigma=np.zeros((d,d))+ e*np.eye(d)

    L=multivariate_normal.logpdf(x,mean=mu,cov=sigma,allow_singular=True).sum()
    
    print(L)
    return L
    

k = pd.DataFrame()

k=pd.concat([k,Xdf.iloc[1:5,:]])
clusterCalculateMLE(k)

(675, 675)
-116.05120203730334

In [ ]:

def get_digit(txt):
    A=[int(s) for s in txt.split() if s.isdigit()]
    return A

In [ ]:
def agglomerative_merge(clusters):
    n=len(clusters)

    C={}
    Cr=[]
    i=0
    while i < (n-1):
        j=i+1
        while j < n:
            C[i,j]=clusterCalculateMLE(pd.concat([clusters[i],clusters[j]]))

    
    while i < len(C):
        a=get_digit(max(C))
        Cr.append(a)

In [92]:

C=[]
C.append(Xdf.loc[0:3,:])

C.append(pd.DataFrame(Xdf.loc[4,:]).T)

test=pd.DataFrame(C[1])
test
df=pd.concat([C[0],(C[1])])
df



#str

,0,1,2,3,4,5,6,7,8,9,...,665,666,667,668,669,670,671,672,673,674
0,193.19,2565.55,3361.85,3810.86,2975.29,1158.14,3624.85,867.60,15.40,3828.42,...,56.710,107.010,14.59,317.230,350.78,41.310,700.730,269.020,136.250,0.000
1,369.52,2362.42,3262.46,2616.13,28.23,861.70,2553.35,440.19,62.21,3341.44,...,146.060,310.320,31.42,177.890,145.00,20.800,150.310,184.260,259.510,19.740
2,169.81,1861.83,2967.65,2563.59,41.46,1003.13,2186.26,435.66,17.39,3021.26,...,68.875,533.595,67.47,233.535,505.31,16.370,352.660,153.905,183.985,42.830
3,305.46,2340.89,3473.33,2876.46,2201.87,1006.68,2120.11,470.53,543.77,3004.02,...,397.170,207.935,9.26,302.845,299.91,22.695,333.215,293.380,149.810,132.565
4,413.63,2317.04,3340.84,3354.31,4.09,1380.59,2648.59,750.58,46.62,3190.31,...,280.920,344.320,122.49,236.580,306.09,25.360,24.350,260.770,186.130,93.170